//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "new"
 * f1 -> PrimaryExpressionWithTrailingFxnCallExpList()
 * f2 -> FunctionCallExpressionList()
 * </PRE>
 */
public class AllocationExpression implements Node {
   public NodeToken f0;
   public PrimaryExpressionWithTrailingFxnCallExpList f1;
   public FunctionCallExpressionList f2;

   public AllocationExpression(NodeToken n0, PrimaryExpressionWithTrailingFxnCallExpList n1, FunctionCallExpressionList n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public AllocationExpression(PrimaryExpressionWithTrailingFxnCallExpList n0, FunctionCallExpressionList n1) {
      f0 = new NodeToken("new");
      f1 = n0;
      f2 = n1;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

