//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> Permissions(false)
 * f1 -> &lt;IDENTIFIER&gt;
 * f2 -> ( "," Permissions(false) &lt;IDENTIFIER&gt; )*
 * f3 -> ( "..." )?
 * </PRE>
 */
public class Arglist implements Node {
   public Permissions f0;
   public NodeToken f1;
   public NodeListOptional f2;
   public NodeOptional f3;

   public Arglist(Permissions n0, NodeToken n1, NodeListOptional n2, NodeOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   
   public int[] cachedValue;
}

