//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>

 * f0 -> "callee"
 * </PRE>
 */
public class CalleePrimaryPrefix implements Node {
   public NodeToken f0;

   public CalleePrimaryPrefix(NodeToken n0) {
      f0 = n0;
   }

   public CalleePrimaryPrefix() {
      f0 = new NodeToken("callee");
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

