//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "("
 * f1 -> PrimaryExpressionNotFunction()
 * f2 -> ")"
 * f3 -> PrimaryExpression()
 * </PRE>
 */
public class CastExpression implements Node {
   public NodeToken f0;
   public PrimaryExpressionNotFunction f1;
   public NodeToken f2;
   public PrimaryExpression f3;

   public CastExpression(NodeToken n0, PrimaryExpressionNotFunction n1, NodeToken n2, PrimaryExpression n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public CastExpression(PrimaryExpressionNotFunction n0, PrimaryExpression n1) {
      f0 = new NodeToken("(");
      f1 = n0;
      f2 = new NodeToken(")");
      f3 = n1;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

