//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> LogicalOrExpression()
 * f1 -> ( "?" LogicalOrExpression() ":" LogicalOrExpression() )?
 * </PRE>
 */
public class ConditionalExpression implements Node {
   public LogicalOrExpression f0;
   public NodeOptional f1;

   public ConditionalExpression(LogicalOrExpression n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

