//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> RelationalExpression()
 * f1 -> ( ( "==" | "!=" ) RelationalExpression() )*
 * </PRE>
 */
public class EqualityExpression implements Node {
   public RelationalExpression f0;
   public NodeListOptional f1;

   public EqualityExpression(RelationalExpression n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

