//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>

 * f0 -> "eval"
 * f1 -> Expression()
 * f2 -> ";"
 * </PRE>
 */
public class EvalBlock implements Node {
   public NodeToken f0;
   public Expression f1;
   public NodeToken f2;

   public EvalBlock(NodeToken n0, Expression n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public EvalBlock(Expression n0) {
      f0 = new NodeToken("eval");
      f1 = n0;
      f2 = new NodeToken(";");
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

