//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> ScopeBlock()
 *       | VariableDeclarationBlock()
 *       | FunctionDeclaration()
 *       | TryStatement()
 *       | ForLoopStatement()
 *       | CollectionForLoopStatement()
 *       | WhileLoopStatement()
 *       | ConditionalStatement()
 *       | SynchronizedStatement()
 *       | ReturnStatement()
 *       | BreakStatement()
 *       | ContinueStatement()
 *       | ExpressionBlock()
 *       | ThrowBlock()
 *       | ImportBlock()
 *       | MixinBlock()
 *       | EvalBlock()
 * </PRE>
 */
public class EvaluationUnit implements Node {
   public NodeChoice f0;
    
   public boolean isStatic = false;

   public EvaluationUnit(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

