//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> Expression()
 * f1 -> ";"
 * </PRE>
 */
public class ExpressionBlock implements Node {
   public Expression f0;
   public NodeToken f1;

   public ExpressionBlock(Expression n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public ExpressionBlock(Expression n0) {
      f0 = n0;
      f1 = new NodeToken(";");
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

