//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>

 * f0 -> Permissions(true)
 * f1 -> "function"
 * f2 -> &lt;IDENTIFIER&gt;
 * f3 -> "("
 * f4 -> ( Arglist() )?
 * f5 -> ")"
 * f6 -> ( "extends" PrimaryExpressionWithTrailingFxnCallExpList() FunctionCallExpressionList() )?
 * f7 -> "{"
 * f8 -> Program(true)
 * f9 -> "}"
 * </PRE>
 */
public class FunctionDeclaration implements Node {
   
   /* Cache fields:
    */
   public Node translated;
   
   /* Parser fields:
    */
   public boolean hasVarInScope = true;  // assume the worst
   public boolean hasFxnInScope = true;  // assume the worst
   
   
   /* Regular JTB fields:
    */
   public Permissions f0;
   public NodeToken f1;
   public NodeToken f2;
   public NodeToken f3;
   public NodeOptional f4;
   public NodeToken f5;
   public NodeOptional f6;
   public NodeToken f7;
   public Program f8;
   public NodeToken f9;

   public FunctionDeclaration(Permissions n0, NodeToken n1, NodeToken n2, NodeToken n3, NodeOptional n4, NodeToken n5, NodeOptional n6, NodeToken n7, Program n8, NodeToken n9, boolean hasVarInScope, boolean hasFxnInScope) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
      f9 = n9;
      this.hasVarInScope = hasVarInScope;
      this.hasFxnInScope = hasFxnInScope;
   }

   public FunctionDeclaration(Permissions n0, NodeToken n1, NodeOptional n2, NodeOptional n3, Program n4) {
      f0 = n0;
      f1 = new NodeToken("function");
      f2 = n1;
      f3 = new NodeToken("(");
      f4 = n2;
      f5 = new NodeToken(")");
      f6 = n3;
      f7 = new NodeToken("{");
      f8 = n4;
      f9 = new NodeToken("}");
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

