//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;IDENTIFIER&gt;
 * </PRE>
 */
public class IdentifierPrimaryPrefix implements Node {
   public NodeToken f0;

   public IdentifierPrimaryPrefix(NodeToken n0) {
      f0 = n0;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

