//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> &lt;INTEGER_LITERAL&gt;
 *       | &lt;FLOATING_POINT_LITERAL&gt;
 *       | &lt;STRING_LITERAL&gt;
 *       | &lt;REGEXP_LITERAL&gt;
 *       | "true"
 *       | "false"
 *       | "null"
 *       | "undefined"
 * </PRE>
 */
public class Literal implements Node {
   public NodeChoice f0;

   public Literal(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

