//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> BitwiseOrExpression()
 * f1 -> ( "&&" BitwiseOrExpression() )*
 * </PRE>
 */
public class LogicalAndExpression implements Node {
   public BitwiseOrExpression f0;
   public NodeListOptional f1;

   public LogicalAndExpression(BitwiseOrExpression n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

