//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(oscript.visitor.Visitor v);
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu);

}

