//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> TypeExpression()
 * f1 -> ( "++" | "--" )?
 * </PRE>
 */
public class PostfixExpression implements Node {
   public TypeExpression f0;
   public NodeOptional f1;

   public PostfixExpression(TypeExpression n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

