//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> VariableDeclaration()
 *       | Expression()
 * </PRE>
 */
public class PreLoopStatement implements Node {
   public NodeChoice f0;

   public PreLoopStatement(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

