//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> ThisPrimaryPrefix()
 *       | SuperPrimaryPrefix()
 *       | CalleePrimaryPrefix()
 *       | ArrayDeclarationPrimaryPrefix()
 *       | IdentifierPrimaryPrefix()
 *       | ParenPrimaryPrefix()
 *       | Literal()
 * </PRE>
 */
public class PrimaryPrefixNotFunction implements Node {
   public NodeChoice f0;

   public PrimaryPrefixNotFunction(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

