//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> ( EvaluationUnit() )*
 * </PRE>
 */
public class Program implements Node {
   public NodeListOptional f0;
   
   public Program staticNodes = null;
   
   public Program(NodeListOptional n0, boolean bogus) {
      f0 = n0;
   }

   public Program(NodeListOptional n0) {
      f0 = n0;
      
      NodeListOptional nlo = null;
      for( int i=0; i<f0.nodes.size(); i++ ) {
          EvaluationUnit eu = (EvaluationUnit)(f0.nodes.elementAt(i));
          if( eu.isStatic ) {
              if( nlo == null ) {
                  nlo = new NodeListOptional();
              }
              nlo.addNode(eu);
              f0.nodes.remove(i--);
          }
      }
      if( nlo != null ) {
          staticNodes = new Program( nlo, false );
      }
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   
   public oscript.NodeEvaluator nodeEvaluator;
}

