//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "."
 * f1 -> &lt;IDENTIFIER&gt;
 * </PRE>
 */
public class PropertyIdentifierPrimaryPostfix implements Node {
   public NodeToken f0;
   public NodeToken f1;

   public PropertyIdentifierPrimaryPostfix(NodeToken n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public PropertyIdentifierPrimaryPostfix(NodeToken n0) {
      f0 = new NodeToken(".");
      f1 = n0;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

