//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "this"
 * </PRE>
 */
public class ThisPrimaryPrefix implements Node {
   public NodeToken f0;

   public ThisPrimaryPrefix(NodeToken n0) {
      f0 = n0;
   }

   public ThisPrimaryPrefix() {
      f0 = new NodeToken("this");
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

