//
// Generated by JTB 1.2.1
//

package oscript.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * f0 -> "try"
 * f1 -> EvaluationUnit()
 * f2 -> ( "catch" "(" Expression() &lt;IDENTIFIER&gt; ")" EvaluationUnit() )*
 * f3 -> ( "catch" "(" &lt;IDENTIFIER&gt; ")" EvaluationUnit() )?
 * f4 -> ( "finally" EvaluationUnit() )?
 * </PRE>
 */
public class TryStatement implements Node {
   public NodeToken f0;
   public EvaluationUnit f1;
   public NodeListOptional f2;
   public NodeOptional f3;
   public NodeOptional f4;

   public TryStatement(NodeToken n0, EvaluationUnit n1, NodeListOptional n2, NodeOptional n3, NodeOptional n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public TryStatement(EvaluationUnit n0, NodeListOptional n1, NodeOptional n2, NodeOptional n3) {
      f0 = new NodeToken("try");
      f1 = n0;
      f2 = n1;
      f3 = n2;
      f4 = n3;
   }

   public void accept(oscript.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(oscript.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
}

