/*=============================================================================
 *     Copyright Texas Instruments 2003.  All Rights Reserved.
 *   
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 * 
 * $ProjectHeader: $
 */


package oscript;


/**
 * Version name/number info.  This file is autogenerated from Version.java.in.
 * 
 * @author Rob Clark (rob@ti.com)
 * <!--$Format: " * @version $Revision$"$-->
 * @version ??
 */
public final class Version
{
  private static final int    VERSION_NUMBER = 1917;
  private static final String VERSION_NAME   = "2.10.4";
  
  /**
   * Get the svn repository version number
   * 
   * @return an integer indicating the revision number of the src
   *    code repository from which the interpreter was built
   */
  public static int getVersionNumber() { return VERSION_NUMBER; }
  
  /**
   * Get svn root path directory name, ie. either "trunk", a branch name,
   * or a tag name.
   * 
   * @return a string 
   */
  public static String getVersionName() { return VERSION_NAME; }
}



/*
 *   Local Variables:
 *   tab-width: 2
 *   indent-tabs-mode: nil
 *   mode: java
 *   c-indentation-style: java
 *   c-basic-offset: 2
 *   eval: (c-set-offset 'substatement-open '0)
 *   eval: (c-set-offset 'case-label '+)
 *   eval: (c-set-offset 'inclass '+)
 *   eval: (c-set-offset 'inline-open '0)
 *   End:
 */

